on:
  push:
    branches:
      - master
name: Deploy to Main Branch

jobs:
  deploy:
    name: Deploy - Staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

